---
- hosts: balancer
  sudo: yes

  vars:
    http_port: 80


  tasks:

    - name: install packages
      apt: name=haproxy update_cache=yes state=latest

    - name: enable haproxy
      lineinfile: dest=/etc/default/haproxy regexp="ENABLED=" line="ENABLED=1" state=present
      notify:
        - restart haproxy

    - name: connfigure haproxy.cfg file
      blockinfile:
        dest: /etc/haproxy/haproxy.cfg
        block: |
          frontend haproxy_in
          	bind *:80
          	default_backend haproxy_http

          backend haproxy_http
          	balance roundrobin
          	mode http
          	stats enable
          	stats uri /haproxy?stats
          	server webserver1 192.168.1.114:8081 check
          	server webserver2 192.168.1.133:8081 check


  handlers:
    - name: restart haproxy
      service: name=haproxy state=restarted